/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 10-27-2020
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   10-27-2020   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
@isTest
public class PM_generateInvoicePDF_CTRLTest {
/*
    @testSetup 
    static void setup() {
        // Create common test Contact
        Contact contactObject = TestDataFactory.createContact();
        Invoice__c germanInvoiceObj = TestDataFactory.createInvoice('German', contactObject.Id );
        Invoice__c englishInvoiceObj = TestDataFactory.createInvoice('English', contactObject.Id );
    }

    @isTest static void processGermanInvoice() {

        List <Invoice__c> currentInvoiceList = [select Id, BillingContact__c, Status__c, Name, Language__c FROM Invoice__c where Language__c='German'];
        
        Test.startTest();
        PM_generateInvoicePDF_CTRL.executeActivitiesOnInvoice(currentInvoiceList.get(0).Id, 'German');
        Test.stopTest();

    }
*/
    /*@isTest static void processEnglishInvoice() {

        List <Invoice__c> currentInvoiceList = [select Id, BillingContact__c, Status__c, Name, Language__c FROM Invoice__c where Language__c='English'];

        Test.startTest();
        PM_generateInvoicePDF_CTRL.executeActivitiesOnInvoice(currentInvoiceList.get(0).Id, 'English');
        Test.stopTest();

    }*/

}